services:
  caddy-proxy:
    image: ghcr.io/duckinzzz/caddy-proxy:latest
    container_name: caddy-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy-proxy:
    external: true
